language: python
python: 2.7

branches:
    only:
        - master

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=flake8

matrix:
    allow_failures:
        - env: TOX_ENV=flake8

install:
    - travis_retry sudo add-apt-repository -y ppa:gstreamer-developers/ppa
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install -qq bash-completion python-gi gstreamer1.0-plugins-good gstramer1.0-plugins-bad
    - travis_retry pip install tox sphinx
    - "[[ $TOX_ENV == 'py27' ]] && pip install coveralls || true"

script: tox -e $TOX_ENV

# coveralls.io reporting, using https://github.com/coagulant/coveralls-python
# Only report coverage for one version.
after_success:
    - "[[ $TOX_ENV == 'py27' ]] && coveralls || true"

notifications:
    irc:
        channels:
            - "irc.freenode.org#beets"
        use_notice: true
        skip_join: true
