directory: /home/jack/Music/
library: /home/jack/Music/library.blb
import:
    move: yes
paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
    singleton: $albumartist/$title

ui:
    color: no
